language: node_js
node_js:
  - 11
dist: trusty
stages:
#  - lint
#  - test
#  - integration
#  - e2e
  - deploy
branches:
  except:
    - gh-pages
    - l10n_develop
service :
  - docker

env :
  - IMAGE_NAME=938788377650.dkr.ecr.eu-west-1.amazonaws.com/juice-shop:1.0-$TRAVIS_BUILD_NUMBER
addons:
  sonarcloud:
    organization: "thoril-github" 
   
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner
#before_deploy:
#  - rm -rf node_modules
#  - rm -rf frontend/node_modules
#  - npm install --production
after_success:
  - rm -rf node_modules
  - rm -rf frontend/node_modules
  - npm install --production
  - npm run package
  - pip install --user awscli
  - docker build  -t thomas/juice-shop .
  - eval $(aws ecr get-login --region eu-west-1 --no-include-email)
  - docker tag thomas/juice-show $IMAGE_NAME
  - docker push $IMAGE_NAME  
  - aws cloudformation deploy --template-file ./ecs-task.yaml --stack-name ecs-deployment --region eu-west-1 --parameter-override ImageName=$IMAGE_NAME
  - aws cloudformation update-stack --template-body file://./ecs-task.yaml --stack-name ecs-deployment --region eu-west-1 --parameters "ParameterKey=ImageName,ParameterValue=$IMAGE_NAME"
